# Inspired by https://github.com/Swatinem/rust-cache/blob/master/.github/workflows/simple.yml
name: CI/CD

on:  
  push:    
    tags: 
      - v*.*.*
  pull_request:    
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: DCA Ethereum ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3

      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check and test
        run: |
          cargo check
          cargo test
      
      - name: Build release
        run: cargo build --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/dca-onchain
            target/release/dca-onchain.exe
